### ISSUE TITLE
Change description for a more pro link.

### ISSUE THREAD

**Issue by majensen** [linkml/linkml.github.io#1]
To get a better caption than "LinkML blah..."

<img width="414" alt="image" src="https://user-images.githubusercontent.com/82073/140795236-c0b908fd-bb95-409b-ae42-91333e8565f1.png">

may want to update _config.yml ? 

![NCI-02133017-ML11nkml github 10 jensenma$ ack blah](https://user-images.githubusercontent.com/82073/140795793-5fa3681a-3a4d-4755-9c00-8652482d2838.jpeg)

Mark

**Comment by nlharris** [comment]
Sounds like this can be closed?

**Comment by nlharris** [comment]
(I don't have permission to close issues in this repo)
