### ISSUE TITLE
New template suggestion

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml.github.io#5]
see: https://github.com/linkml/linkml.github.io/blob/master/index.md?plain=1#L92

![Screen Shot 2022-09-28 at 08 27 54](https://user-images.githubusercontent.com/88113/192704161-8c384035-f215-4034-aeaa-d5afd605fcbe.png)

The main documentation page points to the archived repo https://github.com/linkml/archived-linkml-model-template . Is the new recommended repository https://github.com/linkml/linkml-project-cookiecutter  ?

**Comment by cmungall** [comment]
good catch! the whole splash page could do with a refresh, but we should fix this first
